CREATE TABLE IF NOT EXISTS users
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    email varchar(320) NOT NULL,
    password varchar(255) NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS movies
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    title varchar(255) NOT NULL,
    rating integer NOT NULL DEFAULT 0,
    watched boolean NOT NULL DEFAULT false,
    poster_path varchar(255),
    overview text,
    popularity double precision NOT NULL DEFAULT 0,
    vote_average double precision NOT NULL DEFAULT 0,
    release_date date NOT NULL,
    movie_id integer NOT NULL,
    CONSTRAINT fk_movies_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_movies_rating
        CHECK (rating IN (-1, 0, 1))
);

CREATE INDEX IF NOT EXISTS ix_movies_user_id
    ON movies (user_id);

CREATE INDEX IF NOT EXISTS ix_movies_user_status
    ON movies (user_id, watched, rating);
